# Generated by Django 3.0.7 on 2020-07-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('conteudo', models.TextField()),
                ('imagem_de_fundo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='aboult',
            name='capa_video',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
