# Generated by Django 3.0.7 on 2020-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0004_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=155)),
                ('descricao', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=55)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('instagran', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
