# Generated by Django 3.0.7 on 2020-07-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0005_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=155)),
                ('profissao', models.CharField(max_length=155)),
                ('declaracao', models.CharField(max_length=155)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboult',
            options={'ordering': ('-id',)},
        ),
    ]
