# Generated by Django 3.0.7 on 2020-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0007_auto_20200709_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('-id',)},
        ),
    ]
