# Generated by Django 3.0.7 on 2020-07-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0008_auto_20200709_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalhes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('titulo_navbar', models.CharField(max_length=55)),
                ('titulo_produtos', models.CharField(max_length=155)),
                ('titulo_perfil', models.CharField(max_length=155)),
                ('titulo_contatos', models.CharField(max_length=155)),
                ('titulo_rodape', models.CharField(max_length=155)),
                ('frase_rodape', models.CharField(max_length=155)),
                ('link_facebook', models.CharField(max_length=155)),
                ('link_twitter', models.CharField(max_length=155)),
                ('link_instagram', models.CharField(max_length=155)),
                ('link_linkedin', models.CharField(max_length=155)),
                ('imagem_fundo_perfil', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='imagetestimonial',
            options={'ordering': ('-id',)},
        ),
    ]
