# Generated by Django 3.0.7 on 2020-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0010_auto_20200711_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalhes',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='detalhes',
            name='titulo_perfil',
        ),
        migrations.AddField(
            model_name='detalhes',
            name='frase_contatos',
            field=models.CharField(default='Frase da sessão contatos', max_length=255),
        ),
    ]
