# Generated by Django 3.0.7 on 2020-07-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0011_auto_20200711_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Titulo da sua Galeria', max_length=155)),
                ('frase_galeria', models.CharField(default='Frase da sua Galeria', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_imagem', models.CharField(default='descrição da imagem', max_length=99, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='onepage.Galeri')),
            ],
        ),
    ]
