# Generated by Django 3.0.7 on 2020-07-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0012_fotogaleria_galeri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'ordering': ('-id',)},
        ),
    ]
